[package]
name = "appendlist"
version = "1.2.0"
authors = ["Daniel Dulaney <dan@dulaney.xyz>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/danieldulaney/appendlist"

[dependencies]
